openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: AquaTrack with user authorization
servers:
  - url: https://aquatrack-duna-server.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  # /auth/send-reset-email:
  #   post:
  #     $ref: ../swagger/paths/auth/send-reset-email/post.yaml
  # /auth/reset-pwd:
  #   post:
  #     $ref: ../swagger/paths/auth/reset-pwd/post.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/users/current/get.yaml
    patch:
      $ref: ../swagger/paths/users/current/patch.yaml
  /water/{waterId}:
    # get:
    #   $ref: ../swagger/paths/water/{waterId}/get.yaml
    delete:
      $ref: ../swagger/paths/water/{waterId}/delete.yaml
    patch:
      $ref: ../swagger/paths/water/{waterId}/patch.yaml
  /water:
    # get:
    #   $ref: ../swagger/paths/water/get.yaml
    post:
      $ref: ../swagger/paths/water/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
